num = int(input("please enter your age:"))
num1 = int(input("please enter your sisters age:"))
num2 = int(input("please enter your fathers age:"))
num3 = int(input("please enter your mothers age:"))
num4 = int(input("please enter your grandmas age:"))
print("you after 20 years will be",num + 20,"years")
print("your sister after 20 years will be:",num1 + 20,"years")
print("your father after 20 years will be:",num2 + 20,"years")
print("your mother after 20 years will be:",num3 + 20,"years")
print("your grandma after 20 years will be:",num4 + 20,"years")